[12.0][MIG] project_stock: Migration from 14.0 to 12.0
OCA/project pull request #1056
Opened 2023-01-19 13:14 UTC by marcelsavegnago

2023-02-10 09:41 UTC, quannguyen1560 requested changes
Please check my comment and fix the pipeline. thank you

2023-02-10 09:41 UTC, quannguyen1560 commented on project_stock/models/project_project.py
> +    def write(self, vals):
You need @api.multi for version 12

2023-02-10 09:41 UTC, quannguyen1560 commented on project_stock/models/project_task.py
> +    def action_cancel(self):
Should have self.ensure_one()

2023-02-10 09:41 UTC, quannguyen1560 commented on project_stock/models/project_task.py
> +    def write(self, vals):
Should have @api.multi

2023-02-10 09:41 UTC, quannguyen1560 commented on project_stock/models/project_task.py
> +    def unlink(self):
Should have @api.multi

2023-02-10 17:14 UTC, marcelsavegnago commented
ping @OCA/community-maintainers 

https://app.travis-ci.com/github/OCA/project/jobs/595702814#L293

```
ERROR: Could not find a version that satisfies the requirement pylint-plugin-utils==0.7 (from -r /home/travis/maintainer-quality-tools/travis/pylint_odoo_requirements.txt (line 1)) (from versions: 0.1, 0.1.1, 0.2, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.6, 0.3, 0.4, 0.5, 0.6)
ERROR: No matching distribution found for pylint-plugin-utils==0.7 (from -r /home/travis/maintainer-quality-tools/travis/pylint_odoo_requirements.txt (line 1))
```

I found an issue reporting the same problem in another repository.
https://github.com/OCA/maintainer-quality-tools/issues/712

2023-02-10 17:31 UTC, marcelsavegnago commented
ping @OCA/project-service-maintainers

2023-02-14 13:00 UTC, marcelsavegnago commented
ping @pedrobaeza @victoralmau

2023-02-14 13:02 UTC, marcelsavegnago commented
ping @quannguyen1560

2023-02-17 09:24 UTC, quannguyen1560 commented
@marcelsavegnago 
Did you add yourself to the[CONTRIBUTORS ?

2023-02-17 19:59 UTC, marcelsavegnago commented
> @marcelsavegnago Did you add yourself to the CONTRIBUTORS ?

done

2023-02-24 09:09 UTC, quannguyen1560 approved these changes
LGTM

2023-02-24 09:11 UTC, pedrobaeza commented
/ocabot merge nobump

2023-02-24 09:37 UTC, merged