[15.0][ADD] project_sale_order_link
OCA/project pull request #1196
Opened 2023-11-13 15:54 UTC by EmilioPascual

This module is glue module that allow you to see all order linked to project, project tasks or employee map following relations:

  * A sale order item is selected in project.
  * A sale order item is selected in project task.
  * A sale order item is selected in project timesheet.
  * A sale order item is selected in project sale line/Employee map.

2023-12-11 04:36 UTC, rafaelbn approved these changes
Functional 👍🏼

2023-12-12 08:08 UTC, Shide requested changes
Seems like this module serves as a base for other purpose like having at hand the order and order lines linked to an order. If this is the case, should be added in the DESCRIPTION.rst file.

**question:** If the purpose of the module is having order_line_link_ids and sale_order_link_ids fields available, suggestions on *.py files can be ignored.

**nitpick:** I think *.xml suggestions must be reviewed regarding the purpose of the module.

2023-12-12 08:08 UTC, Shide commented on project_sale_order_link/views/project_views.xml
> +                    <field name="sale_order_link_ids" attrs="{'invisible': True}" />
No need to add the field because doesn't show nothing.

```suggestion
```

2023-12-12 08:08 UTC, Shide commented on project_sale_order_link/views/project_views.xml
> +                    groups="sales_team.group_sale_salesman_all_leads"
Change group to sale user and the tree view or the action will filter the tasks that the user can see.

2023-12-12 08:08 UTC, Shide commented on project_sale_order_link/models/project.py
> +            project.sale_order_link_ids = order_lines.order_id.ids
Not needed since there is no visible field in the form view. (Check final comments)

```suggestion
```

2023-12-12 08:08 UTC, Shide commented on project_sale_order_link/models/project.py
> +        so_ids = self.sale_order_link_ids.ids
Move order lines choose behaviour to button. (Check final comments)

```suggestion
        so_ids = self.env["sale.order"]
        so_ids |= (
                project.sale_line_id.order_id
                | project.task_ids.sale_line_id.order_id
                | project.timesheet_ids.so_line.order_id
                | project.sale_line_employee_ids.sale_line_id.order_id
         ).ids
```

2023-12-12 08:08 UTC, Shide commented on project_sale_order_link/readme/CONTEXT.rst
> +But in the project you can only see the selected order in the project itself.
I think this file is not needed since DESCRIPTION.rst says the same.

```suggestion
```

2023-12-12 08:08 UTC, Shide commented on project_sale_order_link/readme/USAGE.rst
> +#. Cliack on Smartbutton to see sale orders linked.
```suggestion
#. Click on Smartbutton to see sale orders linked.
```

2023-12-12 08:08 UTC, Shide commented on project_sale_order_link/readme/DESCRIPTION.rst
> +  * A sale order item is selected in project sale line/Employee map
```suggestion
  * A sale order item is selected in project sale line/Employee map
  
Now you have 2 available fields referencing related sale orders and sale order lines on each project.
```

2024-01-10 10:46 UTC, Shide approved these changes

2024-01-10 17:19 UTC, rafaelbn approved these changes
/ocabot merge patch

2024-01-10 17:29 UTC, merged