[17.0][MIG] project_role: Migration to 17.0
OCA/project pull request #1204
Opened 2023-12-12 06:26 UTC by ramiadavid

2024-03-19 12:26 UTC, xavierboes commented
Get an error when using the smart button on a project.

Window action should have:
- domain: [('project_id','=',id)] --> [('project_id','=',active_id)]
- context: {'default_project_id': id} --> {'default_project_id': active_id}

2024-03-20 23:04 UTC, ramiadavid commented
@xavierboes updated

2024-03-21 12:00 UTC, xavierboes commented
Further testing: the project is not visible when opening the Assignment list (view: project_role.project_assignment_tree).
Would leave out the invisible condition (invisible="context.get('default_project_id', False)").

Also, why not add the assignments as a tab/page on the project?

```
            <notebook position="inside">
                <page name="assignments" string="Assignments">
                    <field name="assignment_ids">
                        <tree>
                            <field name="role_id"/>
                            <field name="user_id"/>
                        </tree>
                    </field>
                </page>
            </notebook>

```

2024-03-22 16:28 UTC, ramiadavid commented
@xavierboes 

> the project is not visible when opening the Assignment list (view: project_role.project_assignment_tree).

I'm sorry, but I don't see where the project is not visible, I can see it, can you show me a screenshot?

> Also, why not add the assignments as a tab/page on the project?

I think we should do this as an improvement, to be able to forward to other versions, instead of doing it in the migration, what do you think?

2024-03-23 21:00 UTC, xboes commented
@ramiadavid Project is now visible, seems fixed ✅

2024-04-04 08:52 UTC, xavierboes commented
@ramiadavid : project visibility is still incorrect.

Problem is here:
```html
<field name="project_id" domain="[('active', '=', True)]" invisible="context.get('default_project_id', False)"/>
``` 

Resulting in empty list view:
![image](https://github.com/OCA/project/assets/104941602/88f43481-15f0-4a31-8ce8-5699b0ed1298)


--> Would leave out the "invisible" statement.


Also, would really appreciate the tab/page addition as it improves workability from functional standpoint

2024-04-07 13:30 UTC, ramiadavid commented
@xavierboes Updated

2024-04-07 19:04 UTC, xboes commented
Great, LGTM !

2024-05-01 15:51 UTC, gbtechnology commented
Hello, who should merge this?

2024-05-02 14:23 UTC, pedrobaeza commented
/ocabot migration project_role

2 reviews should be done:

https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#review

2024-06-17 20:07 UTC, alexey-pelykh requested changes

2024-06-17 20:07 UTC, alexey-pelykh commented on project_role/views/project_assignment.xml
> +                <field name="project_id" domain="[('active', '=', True)]" />
`column_invisible` instead of `invisible`, see https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-17.0

2024-07-05 05:40 UTC, ramiadavid commented on project_role/views/project_assignment.xml
> +                <field name="project_id" domain="[('active', '=', True)]" />
done

2024-07-08 14:08 UTC, alexey-pelykh commented on project_role/views/project_project.xml
> +            <notebook position="inside">
Isn't this a new feature?

2024-10-11 12:06 UTC, CasVissers-360ERP approved these changes
Functional review

2024-11-06 20:41 UTC, coleste commented
👍 
what is happening with the new feature?

2024-11-24 16:05 UTC, astirpe approved these changes

2024-11-25 08:39 UTC, alexey-pelykh approved these changes

2025-02-09 17:42 UTC, dreispt approved these changes

2025-02-09 17:42 UTC, dreispt commented
/ocabot merge nobump

2025-02-09 17:49 UTC, merged