[16.0][ADD] task_project_status
OCA/project pull request #1327
Opened 2024-08-21 06:42 UTC by adasatorres

- Hi, this addon allow see the project status on task form view.

2024-08-21 09:02 UTC, flotho requested changes

2024-08-21 09:02 UTC, flotho commented on task_project_status/models/project.py
> +        copy=False,
Hi, thanks for the work.
As your using a related field without store option I don't think you neet copy index ondelete etc...
Yet if your purpose is to be able to group task by project status, you should store the related field and keep those options

2024-09-30 16:26 UTC, flotho approved these changes
LGTM

2024-10-01 09:24 UTC, szalatyzuzanna approved these changes

2024-10-18 17:44 UTC, dreispt commented
/ocabot merge nobump

2024-10-18 17:52 UTC, merged