[ADD] Addon: project_required_field_by_stage
OCA/project pull request #1341
Opened 2024-09-26 00:11 UTC by Tiago370

2024-10-07 09:25 UTC, gjotten approved these changes
Functional review, LGTM.

2024-11-13 09:18 UTC, gbrito requested changes

2024-11-13 09:18 UTC, gbrito commented on project_required_field_by_stage/models/project_task.py
> +                        if not getattr(self, "%s" % field.name):
```suggestion
                    if hasattr(rec, field.name) and not getattr(rec, field.name):
```

2024-11-13 09:18 UTC, gbrito commented on project_required_field_by_stage/models/project_task.py
> +            stage = self.env["project.task.type"].search([("id", "=", rec.stage_id.id)])
maybe you can only go through the stages that have required fields assigned.
```suggestion
        stages = self.stage_id.filtered(lambda x: x.required_field_ids)
        for stage in stages:
            fields = (
                self.env["ir.model.fields"]
                .sudo()
                .search([("id", "in", stage.required_field_ids.ids)])
            )
            for rec in self.filtered(lambda x: x.stage_id == stage):
                for field in fields:
                    if hasattr(rec, field.name) and not getattr(rec, field.name):
                        raise error               
```

2025-04-20 12:12 UTC, closed without merging

2026-01-09 16:42 UTC, gfcapalbo commented
@gbrito  this MR was re-created here: https://github.com/OCA/project/pull/1650  , your review suggestions were implemented there.