[MIG] project_task_code: Migration to 17.0
OCA/project pull request #1355
Opened 2024-10-22 16:21 UTC by nedaszilinskas

2024-10-23 09:59 UTC, anikeenko-viktor approved these changes
LGTM!

2024-10-24 12:01 UTC, mtnarjan approved these changes
Looks good!

2024-10-25 11:23 UTC, n17 commented
Looks good to me!

2024-10-25 11:25 UTC, n17 approved these changes

2024-11-22 00:30 UTC, coleste commented on project_task_code/views/project_view.xml
> +            </field>
This change is weird. I don't think it works.
16.0 has a `t-if= / t-else=`, same as 17.0

2025-03-24 12:19 UTC, Abranes approved these changes

2025-05-12 03:49 UTC, etobella commented
/ocabot rebase

2025-05-12 04:25 UTC, etobella commented on project_task_code/views/project_view.xml
> +            </field>
It is true. observe when we use active tasks:
![image](https://github.com/user-attachments/assets/6641fc91-72fb-4ad7-854f-7e2eb8ae335a)
and archived tasks...
![image](https://github.com/user-attachments/assets/5bbaea17-6640-418e-aac3-084a7a90d161)

As you are not answering the comment from @coleste , I will proceed with the PR

2025-05-12 04:25 UTC, etobella requested changes
Fix the kanban

2025-05-12 06:26 UTC, pedrobaeza commented
Superseded by #1499

2025-05-12 06:26 UTC, closed without merging