[18.0] [MIG] project_key: Migration to 18.0
OCA/project pull request #1386
Opened 2024-11-29 14:51 UTC by Borruso

Migration from 16.0 to 18.0

2024-11-29 16:25 UTC, zamberjo commented
If not much changes, can you do the pr to 17.0?

2024-12-16 21:41 UTC, coleste commented on project_key/views/project_key_views.xml
> +    <record id="view_task_list2_extend_with_key" model="ir.ui.view">
again, I'm not sure the external id should be changed unless Odoo does the same thing.

2024-12-18 18:03 UTC, coleste approved these changes
LGTM

2025-01-29 06:37 UTC, zamberjo requested changes

2025-01-29 06:37 UTC, zamberjo commented on project_key/tests/test_task.py
> +            active_model="project.project", id=self.project_1.id
Hard-coded model name instead of active_model.

```sugestion
            model="project.project", id=self.project_1.id
```

2025-01-31 12:39 UTC, zamberjo approved these changes
By the way, can you check the [PR for 17.0](https://github.com/OCA/project/pull/1424)? That way, we kill two birds with one stone.

2025-02-09 17:44 UTC, dreispt approved these changes

2025-04-21 12:40 UTC, BhaveshHeliconia approved these changes
LGTM

2025-04-24 20:24 UTC, andreampiovesana approved these changes
Merge?

2025-05-27 14:23 UTC, jdidderen commented
Can you include this PR https://github.com/OCA/project/pull/1465 in the migration ?

2025-05-27 14:26 UTC, rvalyi commented
> Can you include this PR #1465 in the migration ?

yes, please do a rebase -i to include the migration commits from #1465 or redo the process atop of the 17.0 branch as it's better to have a linear migration history. Other than that it's okay for me.

Also this other one is likely to enter in 16.0 and be nice to cherry-pick https://github.com/OCA/project/pull/1510

2025-06-02 11:04 UTC, dreispt commented
Merged with #1514

2025-06-02 11:04 UTC, closed without merging