[18.0][MIG] project_task_description_template: Migration to 18.0
OCA/project pull request #1407
Opened 2024-12-20 12:25 UTC by HeliconiaSolutions

2025-03-25 08:26 UTC, acsonefho requested changes
Just a minor change :pray: 
Thanks for this PR :muscle:

2025-03-25 08:26 UTC, acsonefho commented on project_task_description_template/tests/test_project_task.py
> +from odoo.tests.common import TransactionCase
Please use `BaseCommon`
`from odoo.addons.base.tests.common import BaseCommon`.

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-18.0#tasks-to-do-in-the-migration

2025-03-26 10:57 UTC, BhaveshHeliconia commented
@acsonefho, Please Review.it's done.

2025-03-26 14:26 UTC, acsonefho approved these changes

2025-03-31 08:51 UTC, acsonefho commented
@OCA/project-service-maintainers Need review here please :pray:

2025-04-01 22:31 UTC, dreispt approved these changes

2025-04-02 14:36 UTC, marcelsavegnago approved these changes

2025-04-03 07:08 UTC, acsonefho commented
@pedrobaeza Is it possible to merge this one please? :superhero:

2025-04-03 07:11 UTC, rousseldenis approved these changes

2025-04-03 07:11 UTC, rousseldenis commented
/ocabot merge nobump

2025-04-03 07:12 UTC, pedrobaeza requested changes
/ocabot migration project_task_description_template

Tests seems to have been done with AI and they are not bringing value, as they are testing the ORM, not specific features on this module. Please remove them if there's nothing to test, or adapt them to be minimal to just test the module features.

2025-04-03 07:13 UTC, pedrobaeza commented
I have aborted the merge.

2025-04-03 07:25 UTC, rousseldenis commented
> /ocabot migration project_task_description_template
> 
> Tests seems to have been done with AI and they are not bringing value, as they are testing the ORM, not specific features on this module. Please remove them if there's nothing to test, or adapt them to be minimal to just test the module features.

@pedrobaeza I'm curious about that. How do you detect that? Moreover tests are testing the Form onchange that this module introduces, so...

2025-04-03 07:33 UTC, pedrobaeza commented
@rousseldenis there is background with this contributor about that, and:

![imagen](https://github.com/user-attachments/assets/77eb772f-e0f7-41c4-8104-b9cfc4ccb330)

2025-04-03 07:35 UTC, rousseldenis commented
> @rousseldenis there is background with this contributor about that

Ok. Didn't see it.

@BhaveshHeliconia Could you remove unnecessary tests ?

2025-04-04 04:57 UTC, BhaveshHeliconia commented
@pedrobaeza, @rousseldenis Please Review.as per suggestions we don't need test cases for standard ORM so remove test folder.

2025-04-04 05:14 UTC, rousseldenis commented
> @pedrobaeza, @rousseldenis Please Review.as per suggestions we don't need test cases for standard ORM so remove test folder.

@BhaveshHeliconia you didn't understand. Just remove the unneeded lines of test. You need to test the onchange at least

2025-04-04 06:38 UTC, BhaveshHeliconia commented
@rousseldenis, Please Review.

2025-08-27 12:24 UTC, ivantodorovich approved these changes

2025-08-28 06:26 UTC, leemannd approved these changes

2025-09-15 08:32 UTC, xavier-bouquiaux approved these changes

2025-09-15 08:34 UTC, xavier-bouquiaux commented
@pedrobaeza, the unneeded tests have been deleted, could we merge this ?

2025-09-15 08:43 UTC, yvaucher commented
/ocabot merge nobump

2025-09-15 08:52 UTC, merged