[9.0] extract project_department
OCA/project pull request #171
Opened 2016-04-27 16:57 UTC by yvaucher

Moving https://github.com/OCA/department/pull/53 here

Depends on https://github.com/OCA/project/pull/170

2016-04-27 17:35 UTC, yvaucher commented on project_department/__openerp__.py
> +views.
to move in README.rst

2016-05-01 15:42 UTC, dreispt commented on project_department/__openerp__.py
> +views.
+1

2016-07-22 00:28 UTC, rafaelbn commented
Hi, @yvaucher just please review README and travis, dependency is merger. We can test it! Thanks!

2017-03-22 20:06 UTC, thinkwelltwd commented
I would like to migrate this module to v10, since our server is not on v9. Is there any reason v9 can't be merged? It looks like the tests are passing.

2017-03-23 11:55 UTC, yvaucher commented
@thinkwelltwd There is just the description to move in `README.rst`

I will fix that in order to let you do the migration for 10.0

2017-03-23 20:15 UTC, thinkwelltwd commented
> I will fix that in order to let you do the migration for 10.0

Ok great, should I wait till this is merged before starting?

2017-03-24 16:00 UTC, yvaucher commented
@thinkwelltwd Just did the change you can rely on those last commits to make your migration

2017-03-30 21:39 UTC, dreispt commented
@yvaucher Can you fix the README?

2017-04-07 01:39 UTC, elicoidal requested changes
Some details

2017-04-07 01:39 UTC, elicoidal commented on project_department/LICENSE
> +OpenERP, Open Source Management Solution
No need this file AFAIK

2017-04-07 01:39 UTC, elicoidal commented on project_department/README.rst
> +* Daniel Reis
Add email @dreispt

2017-04-25 15:27 UTC, yvaucher commented
@dreispt can you be more specific? what should I fix in the readme?

2017-04-26 09:03 UTC, dreispt approved these changes

2017-04-28 08:30 UTC, dreispt commented
Sorry @elicoidal your concerns are minor, so I prefer to move on and merge.

2017-04-28 08:30 UTC, merged

2017-04-28 08:43 UTC, elicoidal commented
:+1: