[MIG] project_task_materials_stock: Migration to 10.0
OCA/project pull request #288
Opened 2017-06-06 16:54 UTC by cubells

- Update manifest file
- Update tests

cc @Tecnativa

2017-06-08 23:41 UTC, rafaelbn commented
Please @cubells review travis:

> 2017-06-07 07:28:36,528 6496 ERROR openerp_test odoo.addons.project_timesheet_currency.tests.test_multicurrency_timesheet: ERROR

2017-06-09 00:00 UTC, rafaelbn requested changes
Tested in runbot:

- Go to a task -> Edit -> go to tab materials in the task and try to add materiala -> It doesn't works

Please review

2017-06-09 00:00 UTC, rafaelbn commented on project_task_material_stock/README.rst
> +* Rafael Blasco <rafabn@antiun.com>
rafael.blasco@tecnativa.com

2017-06-09 00:00 UTC, rafaelbn commented on project_task_material_stock/README.rst
> +* Pedro M. Baeza <pedro.baeza@serviciosbaeza.com>
pedro.baeza@tecnativa.com

2017-06-09 00:00 UTC, rafaelbn commented on project_task_material_stock/README.rst
> +* Carlos Dauden <carlos@incaser.es>
carlos.dauden@tecnativa.com

2017-06-09 00:00 UTC, rafaelbn commented on project_task_material_stock/README.rst
> +* Sergio Teruel <sergio@incaser.es>
sergio.teruel@tecnativa.com

2017-06-09 09:37 UTC, cubells commented
@rafaelbn fixed!

2017-06-12 16:48 UTC, rafaelbn requested changes
Functionally tested 👍 
Travis still fails, please review
Thanks!

2017-06-13 19:08 UTC, cubells commented
@rafaelbn :
travis error is due to project_timesheet_currency module. Error is not related to this migration.

2017-06-14 00:02 UTC, rafaelbn commented
I see, in https://github.com/OCA/project/pull/275 . Maybe is useful to ping @damdam-s @gurneyalex or @guewen to notice about travis error related to `project_timesheet_currency` module and the could make a PR to fix it.

About this PR, as said 👍

2017-06-14 00:02 UTC, rafaelbn approved these changes

2017-06-14 06:31 UTC, gurneyalex commented
@rafaelbn the error is not caused by project_timesheet_currency (Travis is green on 10.0 branch of this project). 

This is a classic error which happens when in the repo you have 2 unrelated modules mod_a and mod_b. mod_b introduces a new required field on a model used by mod_a (e.g. security_lead on res.company, which in the current case is introduced by the dependency on sale_stock). mod_a does not depend on mod_b so the tests of mod_a may be run by travis *before* mod_b and its dependencies are loaded. However the MQT scripts have preinstalled the *dependencies* of all modules in the repository (in our case sale_stock). This means the new column is in database, with a NOT NULL constraint. But the default value is not provided when the record is created because sale_stock is not loaded in memory yet => broken CI. 

Ways out of this:

* make project_timesheet_currency depend on sale_stock (I'm :-1: on this)
* split the tests in travis.yml to have the module depending on sale_stock tested separately from the ones who don't
* change the offending tests in all modules not depending on sale_stock and creating a res.company to be decorated with [at_install(False)](https://github.com/odoo/odoo/blob/10.0/odoo/tests/common.py#L55) and [post_install(True)](https://github.com/odoo/odoo/blob/10.0/odoo/tests/common.py#L68) -> this will make these tests run after all the modules have been loaded.

2017-06-18 23:31 UTC, pedrobaeza commented
Thanks for the explanation @gurneyalex.

@cubells Please use method 3 in the tests of this module.

2017-06-18 23:34 UTC, pedrobaeza requested changes
Plus the change in the test

2017-06-18 23:34 UTC, pedrobaeza commented on project_task_material_stock/README.rst
> +#. Go to Project -> Configuration - > Settings and enable option
Is this needed on 10.0?

2017-06-18 23:34 UTC, pedrobaeza commented on project_task_material_stock/README.rst
> +#. Move task to an stage on consume material are activated and moves and
s/on consume material are/where "Consume material" check is

2017-06-18 23:34 UTC, pedrobaeza commented on project_task_material_stock/__manifest__.py
> +    "author": "Antiun Ingeniería S.L.,"
Remove Antiun

2017-06-18 23:34 UTC, pedrobaeza commented on project_task_material_stock/__manifest__.py
> +    "application": False,
Add 'website' key and you can remove this one.

2017-08-09 14:13 UTC, dreispt commented
@pedrobaeza There is a new commit, can you check?

2017-08-09 15:23 UTC, pedrobaeza approved these changes
I have rebased the branch and everything is alright, so I merge.

2017-08-09 15:23 UTC, merged