[MIG] project_task_materials_analytic_partner module: migration to 10.0
OCA/project pull request #290
Opened 2017-06-13 20:19 UTC by cubells

Depends on
- [ ] #288 

Migration of module project_task_materials_analytic_partner to version 10.0

- Change module name
- Update README
- Update views

cc @ Tecnativa

2017-06-18 23:37 UTC, pedrobaeza requested changes

2017-06-18 23:37 UTC, pedrobaeza commented on project_task_material_analytic_partner/README.rst
> +Using this partner, when you consume these materials, the target of the invoice
Change this text to reflect better the purpose of the module (as in 10.0, there's no invoicing of analytic lines):
```
Using this partner, when you consume the materials, the other partner field in the generated analytic lines will be this one instead the one in the project.
```

2017-08-22 17:36 UTC, cubells commented
All is :green_heart: 

Ready to approve.  :smile: 

cc @Tecnativa

2017-08-22 23:02 UTC, pedrobaeza commented
Runbot is still complaining about a missing module. I'm rebuilding again to see.

2017-08-22 23:27 UTC, pedrobaeza commented
No luck. Please be sure you have properly rebase and if so, close this PR and open another one.

2017-08-23 08:12 UTC, cubells commented
Close this pr in order to rebuild runbot correctly with a new pr: https://github.com/OCA/project/pull/310

2017-08-23 08:12 UTC, closed without merging