[ADD] - Added Project Parent module
OCA/project pull request #326
Opened 2017-10-05 07:52 UTC by YogeshMahera-SerpentCS

- Added Project Parent Module

2017-10-05 07:56 UTC, elicoidal commented
@pedrobaeza @dreispt your feeling? (we need it for Business Requirements)

2017-10-05 07:58 UTC, elicoidal reviewed
No python at all?

2017-10-05 07:58 UTC, elicoidal commented on project_parent/__manifest__.py
> +# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html).
Add Elico copyright

2017-10-05 07:58 UTC, elicoidal commented on project_parent/__manifest__.py
> +    'author': 'Odoo Community Association (OCA)',
Add Elico

2017-10-05 07:58 UTC, elicoidal commented on project_parent/__manifest__.py
> +    'website': 'https://www.github.com/OCA/account-analytic.git',
adapt

2017-10-05 07:58 UTC, elicoidal commented on project_parent/README.rst
> +* Eric Caudal<eric.caudal@elico-corp.com>
add space after the name

2017-10-05 09:07 UTC, YogeshMahera-SerpentCS commented
@elicoidal Could you please check it

2017-10-05 13:30 UTC, elicoidal requested changes
I modified the README

2017-10-05 13:30 UTC, elicoidal commented on project_parent/views/project_parent.xml
> +    <record model="ir.ui.view" id="projecet_parent_edit_project">
Improve the id

2017-10-05 13:30 UTC, elicoidal commented on project_parent/views/project_parent.xml
> +    <record id="view_project_kanban_inherited_business_requirment" model="ir.ui.view">
Improve the id (not anymore related to BR

2017-10-06 05:35 UTC, YogeshMahera-SerpentCS commented
@elicoidal Could you please review it

2017-10-06 06:04 UTC, elicoidal commented on project_parent/views/project_parent.xml
> +    <record model="ir.ui.view" id="view_project_parent_edit_project">
id then model

2017-10-06 06:04 UTC, elicoidal approved these changes

2017-10-06 06:29 UTC, YogeshMahera-SerpentCS commented
@elicoidal

2017-10-06 11:37 UTC, elicoidal commented
@pedrobaeza @dreispt: shall we proceed here? Shall we apply the changes directly in account_analytic_parent?

2017-10-07 10:07 UTC, pedrobaeza commented
It can make sense to have a different project hierarchy than analytic hierarchy, as not all accounts are projects, and not all possible parent accounts are also projects.

Then, I think you can continue with this module.

2017-10-07 10:11 UTC, pedrobaeza requested changes
You need to change the approach of the module as outlined in the comment.

2017-10-07 10:11 UTC, pedrobaeza commented on project_parent/__manifest__.py
> +        Project Patent.""",
Don't put summary if it's the same than the name, and it contain a typo.

2017-10-07 10:11 UTC, pedrobaeza commented on project_parent/__manifest__.py
> +        'account_analytic_parent',
Don't depend on this one and create your own field parent_project_id as many2one reference to project.

2017-10-07 10:11 UTC, pedrobaeza commented on project_parent/views/project_parent.xml
> +              <filter string="Parent" icon="terp-folder-orange"
icon is deprecated

2017-10-09 06:49 UTC, YogeshMahera-SerpentCS commented
@elicoidal @pedrobaeza Could you please review it

2017-10-09 07:59 UTC, elicoidal approved these changes
LGTM (functional tests)

2017-10-10 11:31 UTC, pedrobaeza commented on project_parent/models/account_analytic_account.py
> +        string='Parent Analytic Account'
Parent Project

2017-10-10 12:10 UTC, YogeshMahera-SerpentCS commented
@pedrobaeza AMENDED Changes

2017-10-10 13:41 UTC, pedrobaeza approved these changes

2017-10-10 13:41 UTC, merged

2017-10-10 17:35 UTC, elicoidal commented
Thanks @pedrobaeza