[11.0][IMP] project_task_dependency: Auto arranging
OCA/project pull request #403
Opened 2018-07-13 14:25 UTC by tarteo

Adds an setting which enables arranging start and end dates of tasks based on their dependencies. This feature is optional and can be turned on in the project settings.

![auto arrange](https://user-images.githubusercontent.com/10028499/44571079-0c5eec00-a780-11e8-9c99-b813879ff93e.gif)

2018-08-06 10:17 UTC, astirpe requested changes

2018-08-06 10:17 UTC, astirpe commented on project_task_dependency/__manifest__.py
> +    'version': '11.0.1.1.1',
Should be `'11.0.1.1.0'`

2018-08-06 10:17 UTC, astirpe commented on project_task_dependency/models/__init__.py
> +# Copyright 2016 Onestein (<http://www.onestein.eu>)
No need of Copyright in the `__init__.py` files.

2018-08-07 10:15 UTC, astirpe approved these changes

2018-08-24 07:04 UTC, astirpe commented
@tarteo it would be nice if you can add some screenshots that show the effect of this feature in a timeline view.
This module provides a feature that is useful but also very cool if you see it in action on the timeline. :wink:

2018-08-24 07:34 UTC, tarteo commented
I've updated the description with a little video of how it works.

2018-08-27 15:36 UTC, pedrobaeza commented
I'm not sure about this, as this is not taking into account weekends and days off. I think we should move this to the schedule planning module we are doing. What do you think?

2018-08-28 08:32 UTC, tarteo commented
@pedrobaeza If the arranging can be done on the fly on tasks, then I agree. I'll keep my branch so you can use the code of it if you want.

2018-08-28 08:37 UTC, pedrobaeza commented
Not yet, but it can be added using current module methods for skipping days off.

2018-11-24 19:10 UTC, pedrobaeza commented
Are you going to continue with this? The branch has conflicts.

2018-11-27 08:10 UTC, tarteo commented
@pedrobaeza I have no time for this at the moment, I'll close this one and try to put it project_schedule another time.

2018-11-27 08:10 UTC, closed without merging

2018-11-27 08:13 UTC, tarteo commented
And with the addition of https://github.com/OCA/web/pull/1024 this is not really adding much anymore.

2018-11-27 08:14 UTC, pedrobaeza commented
Certainly...