[10.0][BACKPORT] project_task_add_very_high
OCA/project pull request #409
Opened 2018-07-25 14:05 UTC by gaelTorrecillas

Use 3 priority level on tasks (v10.0)

2018-07-26 14:53 UTC, tarteo requested changes
High is already in Odoo project module: https://github.com/odoo/odoo/blob/f05b10ce4984c10be9a9664f17f093ba2ec5ee85/addons/project/models/project.py#L330

2018-07-27 10:10 UTC, gaelTorrecillas commented
@tarteo I understand your message and suggestion, but we need to 3 stars, so add one priority.
I backported from 11.0 to 10.0
https://github.com/OCA/project/blob/11.0/project_task_add_very_high/models/project_task.py#L11

I don't know how to rename le 2nd and 3rd priorities, I used the same name of 11.0

2018-07-27 12:36 UTC, tarteo commented
@gaelTorrecillas Very High and Critical?

2018-07-31 11:34 UTC, AaronHForgeFlow reviewed
Why changing this? This will require a change in the version number, a migration script and also be ported to v11. Is it really necessary?

2018-08-21 09:05 UTC, flotho commented
Hi @aheficent , @tarteo ,
@gaelTorrecillas and I are probably misunderstanding your comment.
The main reason of this change is that we need those 3 level for a customer working in v10.0. And as we love to share our work, we made this PR.
@aheficent , of course you're right regarding the version number and @gaelTorrecillas changed this. But we don't really understood the part of the migration script. Datas are actually stored and expressed in filters with the first part of the tuple for selection field so that all the filter will still correct. 
If somebody want to use this module, he should be aware of the fact that the priority range will change. Our last proposal would be to implement a full rewrite of the values of this selectio  so that it could match to the v11 release.
@aheficent , what's your point of view for this.

regards

2018-08-21 09:19 UTC, astirpe requested changes
`def uninstall_hook()` must be updated accordingly, since a new value `3` was added and it must be correctly handled while uninstalling the module.

Migration script to V11 is not necessary IMO

2018-08-21 09:19 UTC, astirpe commented on project_task_add_very_high/models/project_task.py
> +        ])
Do not remove the newline at the end of the file

2018-08-21 09:19 UTC, astirpe commented on project_task_add_very_high/__manifest__.py
> +    "version": "10.0.1.0.1",
Version should be 10.0.1.1.0 at least

2018-08-21 09:30 UTC, astirpe commented
Oh and I forgot to say ... also the readme and the screenshots must be updated accordingly

2018-09-11 10:22 UTC, gaelTorrecillas commented
Hello, 

@astirpe I changed readme.

2018-09-11 10:30 UTC, astirpe commented
@gaelTorrecillas thanks! Could you also update the `def uninstall_hook()` ?

2018-09-11 10:59 UTC, tafaRU requested changes
Also please check Travis and squash a bit the commits.
Thanks!

2018-09-11 10:59 UTC, tafaRU commented on project_task_add_very_high/models/project_task.py
> +        ('3', 'critical')
It would be better to start with a capital letter: `s/critical/Critical`

2018-09-11 10:59 UTC, tafaRU commented on project_task_add_very_high/models/project_task.py
> +
no newline at the end of file

2018-09-19 08:59 UTC, gaelTorrecillas commented
Hello,

 @astirpe, I updated this function.
@tafaRU I changed the code to be accepted by travis.

2018-09-19 09:34 UTC, tafaRU commented
@gaelTorrecillas, it seems https://github.com/OCA/project/pull/409/files#r216627182 hasn't been attended, isn'it?

2018-09-19 09:58 UTC, gaelTorrecillas commented
@tafaRU I'm sorry, with commit revert, I forgot to add this change.

I'm doing it now.

2018-09-19 11:44 UTC, tafaRU commented
@gaelTorrecillas, ok thanks, could you also please squash your commits in order to keep only the meaningfull ones?

2018-09-19 11:47 UTC, astirpe commented
@gaelTorrecillas You also may want to add yourself in the Contributors list.

2018-09-19 13:43 UTC, gaelTorrecillas commented
@tafaRU, @astirpe I deleted all commits.
but when I verified Travis was not successful.( build #2145).
but I have check one other Travis Build #2146 was successful (for this PR).
I wait your opinion to know how to solve this problem.

2018-09-19 14:29 UTC, tafaRU commented
@gaelTorrecillas, I just restarted all the Build Jobs at https://travis-ci.org/OCA/project/builds/430537214

2018-09-20 07:48 UTC, gaelTorrecillas commented
@tafaRU thank you.
All checks have passed.

2018-09-20 07:54 UTC, astirpe approved these changes

2018-09-20 09:37 UTC, flotho approved these changes
LGTM

2018-09-20 09:47 UTC, tafaRU approved these changes

2018-09-20 11:56 UTC, tarteo approved these changes

2018-09-20 12:11 UTC, AaronHForgeFlow reviewed
@flotho I see your point here, it is not reducing the range but making it bigger. But in v11 we have shorter range and we need to parse then the critical priority to something else. Either that or introduce the same change in v11.
Anyway I tested and it worked. I will not block this.

2018-09-21 07:25 UTC, AaronHForgeFlow approved these changes
:+1:  Merging, as approved by the original author of the module. Tested on runbot.

2018-09-21 07:27 UTC, merged