[11.0][FIX] Copying dependencies in project_task_dependency
OCA/project pull request #425
Opened 2018-09-05 09:29 UTC by tarteo

Fixes https://github.com/OCA/project/issues/422

2018-09-06 09:11 UTC, astirpe requested changes

2018-09-06 09:11 UTC, astirpe commented on project_task_dependency/models/project_task.py
> +            res = super(ProjectTask, self).copy(default)
This line could be moved before the `if`. This way you can avoid the `else`.

2018-09-06 09:18 UTC, astirpe commented on project_task_dependency/models/project_task.py
> +            res = super(ProjectTask, self).copy(default)
And this way the coverage will be not decreased also :)

2018-09-06 09:27 UTC, elicoidal approved these changes
LGTM

2018-09-06 13:18 UTC, astirpe approved these changes

2018-09-17 18:10 UTC, nikul-serpentcs commented on project_task_dependency/__manifest__.py
@tarteo IMHO Add website attribute, for reference  [here](https://github.com/OCA/maintainer-tools/blob/master/template/module/__manifest__.py#L10)

2018-09-18 07:20 UTC, tarteo commented on project_task_dependency/__manifest__.py
Thanks, didn't notice it.

2018-10-10 14:02 UTC, tarteo commented
Can this be merged? :)

2018-10-11 03:52 UTC, nikul-serpentcs approved these changes
Code Review LGTM

2018-10-11 08:12 UTC, merged