[11.0] [ADD] project_task_default_tags
OCA/project pull request #429
Opened 2018-09-19 21:12 UTC by angelmoya

This module add project tags on project, and set as default on new project tasks.

2018-09-19 21:43 UTC, pedrobaeza commented
Use singular in module name.

2018-09-21 06:26 UTC, tarteo requested changes

2018-09-21 06:26 UTC, tarteo commented on project_task_default_tags/README.rst
> +.. image:: https://img.shields.io/badge/license-AGPL--3-blue.png
Can you use the new splitted template for this. https://github.com/OCA/maintainer-tools/tree/master/template/module/readme

2018-09-21 06:26 UTC, tarteo commented on project_task_default_tags/views/project_view.xml
> +        </field>
Please, fix the indentation here.

2018-09-21 06:26 UTC, tarteo commented on project_task_default_tags/tests/test_project_task_default_tags.py
> +        self.assertEqual(self.task.tag_ids, self.project_A.tag_ids)
Can you put `self.task.project_id = self.project_A` here to make sure in this test project_A is certainly the project of the task.

2018-09-21 08:50 UTC, angelmoya commented on project_task_default_tags/tests/test_project_task_default_tags.py
> +        self.assertEqual(self.task.tag_ids, self.project_A.tag_ids)
There is not needed because I created task with project_id = project_A.

2018-09-21 08:53 UTC, angelmoya commented
@pedrobaeza @tarteo 

Done, thanks

2019-03-19 10:44 UTC, dreispt commented on project_task_default_tag/models/project.py
> +    tag_ids = fields.Many2many(
IMO this should be named `default_tag_ids`.
The `tag_ids` fields should be used for a feature adding Projects level Tags.

2022-03-20 12:08 UTC, closed without merging