git log11.0 mig project task send by mail
OCA/project pull request #431
Opened 2018-09-20 11:32 UTC by cubells

2018-09-20 12:03 UTC, chienandalu requested changes
Tested on runbot. Just review LINT and a minor comment below.

2018-09-20 12:03 UTC, chienandalu commented on project_task_send_by_mail/__manifest__.py
> +               "Odoo Community Association (OCA)",
the indenting here isn't correct

2018-09-20 14:15 UTC, pedrobaeza commented on project_task_send_by_mail/readme/DESCRIPTION.rst
> +=========================
Remove the title here

2018-09-21 06:30 UTC, cubells commented
All done

2018-09-21 09:08 UTC, pedrobaeza approved these changes

2018-09-21 13:09 UTC, tafaRU approved these changes
Code review and test.

2018-09-25 09:25 UTC, merged