[MIG] project_task_material_stock: Migration to 11.0
OCA/project pull request #432
Opened 2018-09-21 10:36 UTC by cubells

cc @Tecnativa

2018-09-21 10:47 UTC, pedrobaeza approved these changes
If CIs go well

2018-09-21 12:35 UTC, chienandalu reviewed
Am I doing something wrong?

![peek 21-09-2018 14-34](https://user-images.githubusercontent.com/5040182/45881519-af207f80-bdab-11e8-959a-fa5a69155d82.gif)

2018-09-24 10:05 UTC, cubells commented
@chienandalu your are right. I fix this problem soon.

2018-09-25 08:44 UTC, cubells commented
@chienandalu can you retest this pr? thanks.

2018-09-25 09:24 UTC, chienandalu approved these changes
Great! Now works fine :slightly_smiling_face:

2018-09-25 09:28 UTC, pedrobaeza requested changes

2018-09-25 09:28 UTC, pedrobaeza commented on project_task_material_stock/README.rst
> +* Tecnativa <https://www.tecantiva.com>:
Incorrect URL and you should put correctly the link format in RST:
```
* `Tecnativa <https://www.tecnativa.com>`_:
```

2018-09-25 09:28 UTC, pedrobaeza commented on project_task_material_stock/models/project_task.py
> +        string='Analytic Account',
Put a help attribute explaining for what it is.

2018-09-25 09:28 UTC, pedrobaeza commented on project_task_material_stock/models/project_task.py
>  # Copyright 2015 Antiun Ingeniería S.L. - Sergio Teruel
Change copyright to new company

2018-09-25 09:28 UTC, pedrobaeza commented on project_task_material_stock/models/project.py
>  # Copyright 2015 Antiun Ingeniería S.L. - Sergio Teruel
Change copyright to new company

2018-09-25 09:28 UTC, pedrobaeza commented on project_task_material_stock/__manifest__.py
>  # Copyright 2015 Antiun Ingeniería S.L. - Sergio Teruel
Change copyright to new company

2018-11-13 17:16 UTC, pedrobaeza commented
@cubells please finish this PR

2018-11-14 07:07 UTC, nikul-serpentcs reviewed
Minor Change

2018-11-14 07:07 UTC, nikul-serpentcs commented on project_task_material_stock/tests/test_task_material.py
> +        cls.product2 = cls.env['product.product'].create({
@cubells IMO here use like global variable

2018-11-16 07:23 UTC, cubells commented
I think it's all done @pedrobaeza

2018-11-16 07:30 UTC, nikul-serpentcs approved these changes
Thanks, @cubells 

Code Review LGTM

2018-11-16 09:56 UTC, pedrobaeza approved these changes

2018-11-16 10:37 UTC, merged

2018-11-28 10:05 UTC, jcarlosmontoya commented
Hello guys, I just test this module, but when click Consume Materials Stock moves stay always in state assigned, doing something wrong? best regards

2018-11-28 11:09 UTC, jcarlosmontoya commented
@chienandalu Does it work fine this module now?

2018-11-28 11:11 UTC, jcarlosmontoya commented
Note: Stock moves are in assigned status and move.quantity_done always zero, super method _action_done() return empty recordset

2018-11-28 11:26 UTC, cubells commented
@jcarlosmontoya I'll review later.

2018-11-28 11:29 UTC, jcarlosmontoya commented
@cubells Thank you

2018-11-28 11:40 UTC, jcarlosmontoya commented
@cubells I just do this: If you set quantity_done = requested qty (task line product_uom_qty) works fine
Can i do  a PR?

2018-11-28 11:56 UTC, jcarlosmontoya commented
This example shows how to create an move_line_ids for each stock.move before to call _action_done method
https://github.com/odoo/odoo/blob/12.0/addons/stock/models/stock_inventory.py#L430