[12.0] [MIG] project_task_material
OCA/project pull request #458
Opened 2018-12-05 04:55 UTC by anandkansagra

Issue [Reference](https://github.com/OCA/project/issues/435)

2018-12-05 05:57 UTC, alexey-pelykh requested changes

2018-12-05 05:57 UTC, alexey-pelykh commented on project_task_material/__init__.py
> +from . import models
Please add license notice

2018-12-05 05:57 UTC, alexey-pelykh commented on project_task_material/__manifest__.py
> +    "author": "Daniel Reis,"
Please add `website` as per https://github.com/OCA/maintainer-tools/blob/master/template/module/__manifest__.py#L2

2018-12-05 05:57 UTC, alexey-pelykh commented on project_task_material/README.rst
> +.. image:: https://img.shields.io/badge/licence-AGPL--3-blue.svg
Please split into `readme` as per https://github.com/OCA/maintainer-tools/tree/master/template/module/readme

2018-12-05 05:57 UTC, alexey-pelykh commented on project_task_material/views/project_view.xml
> +
License and copyright notice would be great, yet not required

2018-12-05 05:57 UTC, alexey-pelykh commented on project_task_material/tests/common.py
> +        super(TestProjectCases, self).setUp()
Not required, yet just `super()` is ok

2018-12-05 05:57 UTC, alexey-pelykh commented on project_task_material/tests/__init__.py
> +from . import test_create_material_lines
License notice needed

2018-12-05 05:57 UTC, alexey-pelykh commented on project_task_material/models/__init__.py
> +from . import project
License notice needed

2018-12-05 06:14 UTC, nikul-serpentcs commented on project_task_material/tests/common.py
> +        super(TestProjectCases, self).setUp()
> Not required, yet just `super()` is ok

@alexey-pelykh It's not blocking.

2018-12-05 06:15 UTC, alexey-pelykh commented on project_task_material/tests/common.py
> +        super(TestProjectCases, self).setUp()
Totally agree, thus not required

2018-12-05 08:24 UTC, pedrobaeza commented
Please add #456 in this PR, and rewrite your commit message to be `[MIG] project_task_material_stock: Migration to 12.0` or similar, but not to be `[ADD] ...`, as this is not an addition.

2018-12-05 08:41 UTC, pedrobaeza commented
Sorry, #456 is for `project_task_material_stock`, so it doesn't apply here.

2018-12-05 14:19 UTC, alexey-pelykh approved these changes

2018-12-13 07:32 UTC, nikul-serpentcs approved these changes
Code Review LGTM :+1:

2018-12-13 08:12 UTC, merged