[12.0] [MIG] project_timeline_hr_timesheet
OCA/project pull request #468
Opened 2019-01-22 18:12 UTC by Nikul-Chaudhary

Project Timeline - Timesheet
============================
This module is an addition to the module Project Timeline.
It adds the progress of tasks (hr_timesheet) on the timeline view.

2019-02-06 18:48 UTC, Nikul-Chaudhary commented
@pedrobaeza @OCA/project-service-maintainers Could you please review it?

2019-02-07 03:31 UTC, alexey-pelykh requested changes

2019-02-07 03:31 UTC, alexey-pelykh commented on project_timeline_hr_timesheet/views/project_task_view.xml
> +            <xpath expr="//field[@name='user_id']" position="after">
`xpath` is an overkill here, `field` would be enough

2019-02-07 03:31 UTC, alexey-pelykh commented
Depends on #466

2019-02-07 17:00 UTC, Nikul-Chaudhary commented
@alexey-pelykh Done

2019-02-07 17:08 UTC, alexey-pelykh commented
Will review once `project_timeline` is greenish in runbot

2019-02-08 02:11 UTC, rafaelbn commented
I set WIP until dependencies are merged. Thanks for this contribution!

2019-03-01 09:41 UTC, pedrobaeza commented
Please rebase

2019-03-01 18:08 UTC, Nikul-Chaudhary commented
> Please rebase

rebased

2019-03-03 23:59 UTC, pedrobaeza approved these changes
Squash together the 2 "README.rst" commits.

2019-03-05 13:44 UTC, tarteo requested changes

2019-03-05 13:44 UTC, tarteo commented on project_timeline_hr_timesheet/static/src/less/project_timeline_hr_timesheet.less
> +.o_project_timeline_hr_timesheet_progress {
Use scss instead

2019-03-26 01:37 UTC, emagdalenaC2i approved these changes

2019-03-26 09:32 UTC, merged