[12.0] [MIG] project_timeline_task_dependency
OCA/project pull request #469
Opened 2019-01-22 18:23 UTC by Nikul-Chaudhary

Project Timeline Task Dependencies
==================================  
This module shows arrows between tasks and their dependencies (on the timeline view).

2019-01-22 19:26 UTC, Nikul-Chaudhary commented
@pedrobaeza  I added dependency https://github.com/OCA/project/pull/469/files#diff-58bf4ef7bb17e0cabe9c102156155697R2
but Error : https://travis-ci.org/OCA/project/jobs/483037968#L1100

2019-01-22 19:36 UTC, pedrobaeza commented
In this case it's not working because it belongs to the same repository.

2019-01-23 17:22 UTC, Nikul-Chaudhary commented
@pedrobaeza Ok, We will waiting for merge others

2019-01-24 15:41 UTC, pedrobaeza commented
You can rebase now

2019-01-24 15:42 UTC, pedrobaeza commented
Well, it's not going to work as `project_timeline` is not merged yet... Sorry for telling so soon.

2019-02-06 18:47 UTC, Nikul-Chaudhary commented
> You can rebase now

@pedrobaeza Done

2019-03-01 09:41 UTC, pedrobaeza commented
Please rebase

2019-03-01 18:11 UTC, Nikul-Chaudhary commented
> Please rebase

rebased

2019-03-03 01:53 UTC, pedrobaeza requested changes
Squash together "[UPD] README.rst" commits

2019-03-03 01:53 UTC, pedrobaeza commented on oca_dependencies.txt
> +project https://github.com/Nikul-Chaudhary/project 12-mig-project_timeline
Please remove this one

2019-03-07 10:05 UTC, LoisRForgeFlow approved these changes
:+1:

2019-03-07 10:07 UTC, merged