[12.0][FIX] project_hr: domain on field breaks other modules
OCA/project pull request #573
Opened 2019-09-01 22:06 UTC by alexey-pelykh

2019-09-02 07:26 UTC, Yajo commented
Code looks good. May you explain why exactly this is needed?

2019-09-02 07:28 UTC, alexey-pelykh commented
@Yajo sure, see https://github.com/OCA/project/pull/570#issuecomment-526454611

2019-09-02 07:44 UTC, yajo requested changes
I think the patch is OK, but there's just some unnecessary diff to remove.

Thanks!

2019-09-02 07:44 UTC, Yajo commented on project_hr/__init__.py
> +# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl.html).
Please keep the diff minimal and avoid this change, which adds no real value. The previous link works perfectly fine.

The same across all files.

2019-09-02 07:44 UTC, Yajo commented on project_hr/__manifest__.py
> +    'version': '12.0.1.0.1',
This isn't wrong, but nowadays the bot will bump the version number automatically, so it is not really needed.

2019-09-02 07:44 UTC, Yajo commented on project_hr/views/project_task_views.xml
> +-->
Please do not reformat this code chunk. Just add a line with your copyright if you want.

This was following what's OCA standard, [as you can find in the official module template](https://github.com/OCA/maintainer-tools/blob/771508e99876115c418888bbac7899174662482b/template/module/views/report_name.xml#L2-L3).

2019-09-02 16:01 UTC, ernestotejeda commented
Why remove domain from the model (https://github.com/OCA/project/pull/573/commits/676af34d31f8c1e3196a8e146475110465152fff#diff-001090485663461057b077232b3f33b1L25) and add it to the view (https://github.com/OCA/project/pull/573/commits/676af34d31f8c1e3196a8e146475110465152fff#diff-13c4d9368e1fc91cc0fc7dda883e1961R18) ?
Isn't enough adding `allowed_user_ids` to the views quick_create_task_form (https://github.com/OCA/project/pull/573/commits/676af34d31f8c1e3196a8e146475110465152fff#diff-13c4d9368e1fc91cc0fc7dda883e1961R33) and view_task_tree2 (https://github.com/OCA/project/pull/573/commits/676af34d31f8c1e3196a8e146475110465152fff#diff-13c4d9368e1fc91cc0fc7dda883e1961R47)

2019-09-02 16:02 UTC, alexey-pelykh commented
Mainly because having domain on a field requires all views that refer this field to depend on `project_hr` and include the field manually. This is not good at all.

2019-09-02 19:30 UTC, pedrobaeza commented
OK for the patch.

2019-09-04 23:37 UTC, rafaelbn approved these changes

2019-09-04 23:37 UTC, rafaelbn commented
/ocabot merge patch

2019-09-05 00:23 UTC, merged