14.0 mig project stage closed
OCA/project pull request #765
Opened 2020-11-20 06:20 UTC by Yoshiro009

2020-11-20 17:04 UTC, skeller1 requested changes
LGTM: Functional and technical review on runbot and local machine.

Small change in manifestfile.
LGTM :+1: 

Thank you for supporting OCA

2020-11-20 17:04 UTC, skeller1 commented on project_stage_closed/__manifest__.py
> +    "author": "ACSONE SA/NV," "Tecnativa," "Odoo Community Association (OCA)",
Could you please fix the double quote issue in author string line. This is a result of black,isort run during migration from 12.0 to 13.0.
Thank you

2020-12-08 18:46 UTC, HaraldPanten approved these changes

2020-12-28 16:52 UTC, skeller1 approved these changes

2020-12-29 19:44 UTC, dreispt commented
/ocabot merge minor

2020-12-29 20:43 UTC, merged

2021-05-19 07:40 UTC, petrus-v commented
I think this module is useless in version 14.0 as long `project` module has an `is_closed` field with business logic implement.

What do you think about ? what's the best approach here, at least I'll like to create a new PR with deprecated message in readme also to prevent migration to V15 ?

2021-05-19 08:39 UTC, pedrobaeza commented
Indeed it's totally useless. I would create in this version a new PR with a version 2.0.0, with migration scripts that copy data from `closed` to `is_closed` when set, and update README saying that this module is no longer needed since v14, and remove the rest of the logic.

2021-05-19 08:44 UTC, petrus-v commented
@pedrobaeza thanks for your prompt reply I'll prepare a PR as you suggested !