[IMP] Add a filter for template projects tasks
OCA/project pull request #791
Opened 2021-02-16 16:03 UTC by cvinh

If we go in Tasks Menu, the tasks that belong to a template project are shown. This could lead to an accidental modification of those tasks that are supposed not to be modified

2021-06-03 16:26 UTC, skeller1 requested changes
Functional/Code Review LGTM :+1: 

Please remove manual version change in manifest file.

Thank you

2021-06-05 11:39 UTC, rousseldenis approved these changes
Code review

2021-06-05 11:40 UTC, rousseldenis commented
@cvinh Could you attend @skeller1 comments ?

2022-09-07 14:44 UTC, leemannd approved these changes
The comments have been attended.
@skeller1 Could you squash together the commits, to keep only one?

2022-09-07 15:02 UTC, cvinh commented
> The comments have been attended. @skeller1 Could you squash together the commits, to keep only one?

I'm doing it

2022-09-07 15:21 UTC, leemannd commented
/ocabot merge minor

2022-09-07 15:23 UTC, leemannd commented
Looks good. Thank you for the contribution

2022-09-07 15:44 UTC, merged