[13.0] project_status: add fr_FR translations
OCA/project pull request #792
Opened 2021-02-17 08:27 UTC by tfossoul

2021-06-15 14:31 UTC, leemannd requested changes

2021-06-15 14:31 UTC, leemannd commented on project_status/i18n/fr.po
> +msgstr "Nom"
```suggestion
msgstr "Nom affiché"
```

2021-06-15 14:31 UTC, leemannd commented on project_status/i18n/fr.po
> +msgstr "Spécifier si il s'agit d'un statut de clôture"
```suggestion
msgstr "Spécifier s'il s'agit d'un statut de clôture"
```

2021-06-16 06:56 UTC, leemannd approved these changes

2021-06-24 06:35 UTC, newtratip approved these changes

2021-06-24 06:37 UTC, pedrobaeza commented
This is not the regular way to do translations. Please see https://odoo-community.org/page/translate

2021-06-24 06:37 UTC, closed without merging