[13.0] [MIG] project_task_digitized_signature
OCA/project pull request #802
Opened 2021-03-17 16:59 UTC by bodedra

2021-03-24 17:45 UTC, bodedra commented
@cubells @eLBati @sysadminmatmoz @pedrobaeza I have remove dependency of web_widget_digitized_signature module. It works great.

Now in this PR, we are facing issue with tracking message. So may we remove this tracking message feature because we remove dependency of web_widget_**** module.

Any suggestions are welcome.

2021-03-24 18:01 UTC, bodedra commented
Tested in runbot.

![Screenshot from 2021-03-24 10-59-56](https://user-images.githubusercontent.com/14229503/112361145-4ffb9880-8c90-11eb-856f-2809509d1eef.png)

2021-03-25 07:45 UTC, pedrobaeza commented
The document to mimic was sales order. Is this document now posting the signature in the thread? If so, just see how it's done. If not, it's OK to remove such thing.

2021-03-25 15:25 UTC, bodedra commented
> The document to mimic was sales order. Is this document now posting the signature in the thread? If so, just see how it's done. If not, it's OK to remove such thing.

Nope. This document doesn't post the signature in the thread. I will remove that code from test case. So this PR become green.

JFI, I haven't reviewed posting signature in the sale order.

2021-03-25 16:58 UTC, bodedra commented
@pedrobaeza From portal, when customer signs, it posts PDF in a chatter with content "Order signed by ***Customer Name***". But no such feature in sale order form level. In SO form, just allow attached images in "Customer Signature" tab.

2021-03-25 17:00 UTC, pedrobaeza commented
OK, then we can replicate the same behavior here.

2021-03-25 17:04 UTC, bodedra commented
Here is TODO list for replicate same behavior:

- Add signature template in Task portal view
- Send "Print Task" report in a Task chatter area.

2021-03-25 17:08 UTC, bodedra commented
I have short deadline and will survive for now with as of now functionality. I will continue or contribute later on.

If anyone interested to take on, please feel free to do so.

Thank you @pedrobaeza for your valuable input.

2021-03-25 17:10 UTC, pedrobaeza commented
OK, you can add to the ROADMAP that TODO list. Meanwhile, green Travis is required at least.

2021-03-25 19:37 UTC, bodedra commented
> OK, you can add to the ROADMAP that TODO list. Meanwhile, green Travis is required at least.

It's :green_circle: now.

2021-03-25 20:14 UTC, pedrobaeza requested changes
Several things to do yet:

- Pre-commit stuff is not split from the initial migration commit, so everything is mixed.
- Some commit squashing is needed.
- Update README according new implementation.

2022-07-05 16:22 UTC, dalonsod commented
Hello @pedrobaeza this PR seems to be idle. I'm interested to make v14 migration of this addon, since I should need it in that version, not v13. Is a good approach doing, starting from this PR, the pending tasks you noticed, preserving authority, and then v14 tasks together in a v14 migration PR? Or directly make v12 to v14 migration that could be backported to v13 later, if needed? Or anything else... Thanks!

2022-07-05 16:24 UTC, pedrobaeza commented
You can go directly from v12 to v14

2022-07-06 18:18 UTC, bodedra commented
@pedrobaeza I not only migrated the module but also made it compatible with v13.0. Because there are many changes in base v13.0

@dalonsod  It is best to attend a few @pedrobaeza 's [comment](https://github.com/OCA/project/pull/802#pullrequestreview-621539430) and sign off v13.0 migration and migrate it in v14.0.

2022-07-06 18:20 UTC, pedrobaeza commented
OK then, but that steps are needed then.

2022-07-06 18:27 UTC, bodedra commented
Yup. I agree. That's why I haven't closed this PR.

2022-07-08 08:26 UTC, dalonsod commented
Migration proposal for v14 available in #943 . @bodedra your improvements are covered and contributors mention included

2022-07-11 17:25 UTC, bodedra commented
@dalonsod Wrong migration. I mentioned in https://github.com/OCA/project/pull/802#issuecomment-1176533994 that we will address @pedrobaeza 's comment and complete v13.0 migration first. And then v14.0.

If you don't want to address the above comment, then do the following away v14.0 module migration.
- Check out 14.0 branch
- cherry-pick v13.0 migration commits
- Perform 14.0 module migration

In that way, we will preserve committed history.

2022-07-13 14:08 UTC, dalonsod commented
Hello @bodedra thanks for your comments. We simply followed original suggestion to direct migration from v12 to v14, in order to unblock this, we read your comments later, sorry.

But I'm a little bit confused, when you say "_that we will address @pedrobaeza 's comment and complete v13.0 migration first_", you'll saying you'll resume this? If it's right, we'll wait for it and when it's done, we'll make v14 migration.

2022-07-13 16:29 UTC, bodedra commented
@dalonsod No problem. I am sorry I do not have any availability to continue development work.

You can take over this PR with cherry-pick and I explain both options in above comment.

2022-07-13 16:33 UTC, dalonsod commented
OK thanks @bodedra we'll continue the migration with your comments

2022-07-14 16:40 UTC, dalonsod commented
Hello @bodedra comments attended, you can check #943 v14 migration update, could you review?

![imagen](https://user-images.githubusercontent.com/12749832/179032750-9da5d394-188a-4f25-9274-bec7e9aacf47.png)

* Made initial separated v13.0 pre-commit.
* Cherry-picked your v13 migration commits from here, squashed and preserved authorship. Also updated `INSTALL` file that still referred `web_widget_digitized_signature`, removing it.
* And at last, pre-commit and migration commits for v14.

2022-11-14 08:27 UTC, dalonsod commented
Hello @bodedra could you approve this PR and #943 ? I've made the required changes for both migrations, as suggested.

Thanks in advance!

2022-11-14 17:29 UTC, bodedra commented
Thank you @dalonsod for your contribution. I cannot approve my own PR. I reviewed code again and looks good. 

You can review this and approve it.

2022-11-14 18:02 UTC, bodedra commented
@OCA/project-service-maintainers Would you please review it?

2022-11-15 14:33 UTC, pedrobaeza approved these changes
The scope is very limited, but as added in the ROADMAP, let's not block this anymore

2022-11-15 14:33 UTC, pedrobaeza commented on project_task_digitized_signature/tests/test_project_task_digitized_signature.py
> -        search_domain = [
This test is now useless, as it's not the testing anything related to the module.

2022-11-15 14:33 UTC, pedrobaeza commented
/ocabot merge nobump

2022-11-15 14:35 UTC, pedrobaeza requested changes
Wait! The dependency over `project_task_report` is overkilled. This base module mustn't depend on the other.

2022-11-15 15:38 UTC, pedrobaeza approved these changes
As talked in the 14.0 PR, the dependency is from the beginning, so let's not block this again:

/ocabot merge nobump

2022-11-15 15:50 UTC, merged