[ADD] project_task_markdown
OCA/project pull request #828
Opened 2021-06-25 21:01 UTC by KKamaa

Add markdown to description field in project task as an option from default odoo version 13.0 base on [web_widget_text_markdown](https://github.com/OCA/web/pull/1965)

2021-06-25 23:25 UTC, KKamaa commented
@thomaspaulb This has been migrated, added the branch repo to oca-requirements.txt as stated in[ doc](https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#185oca_dependenciestxt). Travis finds an error in another module not related to this ADD, not sure why.

2021-06-26 07:52 UTC, thomaspaulb requested changes
Hehe... seems you have just found a timezone bug in `project_timesheet_time_control` :-) Since you like to work around midnight, that's when bugs happen if date functions do not correctly take into account the time zone.

2021-06-26 07:52 UTC, thomaspaulb commented on project_task_markdown/models/project_task.py
> +    description = fields.Char(string="Description")
`fields.Text` seems more logical?

2021-06-26 07:52 UTC, thomaspaulb commented on project_task_markdown/readme/CONTRIBUTORS.rst
> +* Tom Blauwendraat <tblauwendraat@therp.nl>
tom@sunflowerweb.nl

2021-06-26 07:52 UTC, thomaspaulb commented
Anyway that test is not ours to fix.. and if you push a fix around daytime I think Travis will be green.

2021-06-28 08:34 UTC, KKamaa commented on project_task_markdown/readme/CONTRIBUTORS.rst
> +* Tom Blauwendraat <tblauwendraat@therp.nl>
fixed

2021-06-28 08:35 UTC, KKamaa commented on project_task_markdown/models/project_task.py
> +    description = fields.Char(string="Description")
This works too, pushed the fix

2021-06-28 15:30 UTC, thomaspaulb approved these changes

2021-06-30 15:12 UTC, gjotten commented
First look on a running instance is promising but I'd like to do some more functional tests before final approval :-)

2021-11-19 10:21 UTC, ajaniszewska-dev approved these changes

2021-11-26 10:42 UTC, dreispt commented
/ocabot merge nobump

2021-11-26 16:23 UTC, merged