14.0 mig project timesheet time control
OCA/project pull request #846
Opened 2021-08-18 13:55 UTC by AntoniRomera

2021-08-19 09:00 UTC, AntoniRomera commented
Hello @pedrobaeza ,

I name you because I don't see project maintainers team, sorry for the inconvenience, in version 14 odoo has added a post_init_hook that creates two rows in "account.analytic.line" in the module "hr_timesheet" then when passing the test of this module indicated me that there was more than one work in progress, the solution that I have reached is to remove those two rows. How do you see it or if someone proposes another solution?

2021-08-19 09:47 UTC, AntoniRomera commented
@newtratip 

Hi, i see you migrated the module "project_key" i have a problem with the mock version, you know how to solve this?

Runbot log:

> [31mERROR: Could not find a version that satisfies the requirement mock==3.0.5 (from odoo14-addon-project-key) (from versions: none)[0m
> [31mERROR: No matching distribution found for mock==3.0.5[0m

2021-08-19 11:08 UTC, pedrobaeza commented
There's another PR for migrating the module in #772 (I haven't checked its status). Please also put a proper PR title for next times for easing the search.

2021-08-19 11:10 UTC, AntoniRomera commented
I close this PR in favour of the other then

2021-08-19 11:11 UTC, pedrobaeza commented
Well, maybe that one is abandoned and not correctly migrated, but we should give a bit more priority to it first.

2021-08-20 06:33 UTC, AntoniRomera commented
We can look at migrating this PR since we have no response from the other one, I am reopening it.
Looking at the travis log, I noticed that for the "project_key" module we have version 3.0.5 of the "mock" dependency which is only supported up to python version 3.5.x, currently using version 3.6.x.

2021-08-20 06:36 UTC, pedrobaeza commented
Why pinning a specific version of the library? Better to let it free.

2021-08-20 06:38 UTC, AntoniRomera commented
I don't really understand, in order to make the modification we have to do a PR of the other module to update the dependency?

2021-08-20 06:42 UTC, pedrobaeza commented
I see this CI correct, so where is the problem you are pointing?

2021-08-20 07:17 UTC, AntoniRomera commented
Sorry, the error is in the runbot, not in the CI.

2021-08-20 07:21 UTC, pedrobaeza commented
But I think that's another thing, as I don't see such error. I think we can continue for now.

2021-08-20 07:25 UTC, AntoniRomera commented
Oh wait, here's an image of the runbot log.
![Error](https://user-images.githubusercontent.com/15333226/130196383-9d357d0d-1773-4892-9222-d1ee5f79ad96.png)

2021-08-20 07:50 UTC, pedrobaeza commented
OK, then add an extra commit releasing such pinning in the module manifest and requirements.txt

2021-08-20 07:56 UTC, pedrobaeza commented
I'm thinking if such requirement is for tests, and then, it shouldn't be put on the manifest, and add `test_requirements.txt` file.

2021-08-20 08:29 UTC, AntoniRomera commented
Have I done it correctly?

2021-08-20 08:46 UTC, pedrobaeza commented
Oh, sorry, the files should be `test-requirements.txt`.

2021-08-20 09:55 UTC, pedrobaeza commented
Uhm, still erroneous... @simahawk do you know what is going on?

2021-08-20 10:11 UTC, simahawk commented
https://app.travis-ci.com/github/OCA/project/jobs/532833784#L1253

Still project_key controller test. What I don't get is why those tests are patching the request if they are using HttpCase. That's wrong IMO.

2021-08-20 10:13 UTC, pedrobaeza commented
Apart from what you comment, Simone, previously, there was a pinned version in mock library. @AntoniRomera maybe the problem is that in `test-requirements.txt`, there's no such pin. Fixing `project_key` tests would be the ideal, but it's more complicated, so let's see if with this, we can continue.

2021-08-20 10:14 UTC, simahawk commented
that's wrong too. `mock` is built-in lib so you should trash https://github.com/OCA/project/blob/14.0/project_key/__manifest__.py#L15 an

2021-08-20 10:17 UTC, pedrobaeza commented
That's what he is trying to do in the commit https://github.com/OCA/project/pull/846/commits/9604348c2388e73f60e7a52142c4e0cd091567ca with this result.

2021-08-20 10:19 UTC, simahawk commented
yes, but
1. there's no need for the requirement (it's built-in)
2. there's no need for mock -> stop mocking :)

2021-08-20 10:20 UTC, simahawk commented
last but not least, the way the request is mocked there is wrong... anyway, just get rid of it.

2021-08-20 10:20 UTC, pedrobaeza commented
Yeah, 1 is covered here, and it fails, and 2 is too much to be asked to a contributor of another module. Maybe do you have the magic recipe to do 2 in a blink?

2021-08-20 10:29 UTC, simahawk commented
no, 1 is NOT covered here: do not add `mock` to `test-requirements.txt` nor anywhere else.
2: remove the mocking and stop worrying about it. That test should not use it at all.
Anyway, here's a blind fix https://github.com/OCA/project/pull/847 let's see.

2021-08-20 12:14 UTC, pedrobaeza commented
Please rebase

2021-08-20 14:27 UTC, AntoniRomera commented
@pedrobaeza Can you view the logs of ci/runbot?

2021-08-23 14:28 UTC, AntoniRomera commented
@pedrobaeza 

Is there a way to avoid the installation of the "project_key" module so that the runbot passes correctly, until PR #848  proceeds?

2021-08-24 06:33 UTC, FernandoRomera approved these changes

2021-08-24 06:34 UTC, pedrobaeza commented
Please avoid merge commits in the PR, and you can squash administrative commits with the previous regular one.

2021-08-24 12:09 UTC, MRomeera approved these changes

2021-08-26 12:37 UTC, AntoniRomera commented
@pedrobaeza @hkapatel-initos 

You can do a review so we can do the merge because I think the runbot is in red and there is no one to do a review and the runbot is in red because of the "project_key" module.

2021-08-26 17:09 UTC, pedrobaeza commented
There's a contamination of other commits/files in this PR. Please clean up it.

2021-08-26 18:31 UTC, pedrobaeza commented
Please don't add merge commits in a PR.

2021-08-26 18:37 UTC, AntoniRomera commented
@pedrobaeza 

Sorry, can you tell me what is wrong, I don't see exactly what I have to clean up, I have done the commits merge.

2021-08-26 18:39 UTC, pedrobaeza commented
You have to rebase, not to merge/pull. Now the final commit is including again a lot of undesired changes.

2021-08-26 19:32 UTC, AntoniRomera commented
@pedrobaeza 

Did I get it right this time? Sorry for the inconvenience

2021-08-26 20:29 UTC, pedrobaeza requested changes

2021-08-26 20:29 UTC, pedrobaeza commented on project_timesheet_time_control/hooks.py
> +            analytic_line_ids.unlink()
This is not correct, as it's destructing data.

2021-08-26 20:29 UTC, pedrobaeza commented on project_timesheet_time_control/security/ir.model.access.csv
> +access_hr_timesheet_switch_portal,access_hr_timesheet_switch portal,model_hr_timesheet_switch,base.group_user,1,1,1,1
This should be put to the timesheet user

2021-08-27 04:31 UTC, hkapatel-initos commented
Can you please resolve this  WARNING?
https://app.travis-ci.com/github/OCA/project/jobs/534054346#L1512

2021-08-27 06:05 UTC, AntoniRomera commented
> Can you please resolve this WARNING?
> https://app.travis-ci.com/github/OCA/project/jobs/534054346#L1512

Solved

2021-08-27 06:06 UTC, AntoniRomera commented on project_timesheet_time_control/hooks.py
> +            analytic_line_ids.unlink()
Sorry, i fix this by stop any running timer in testss

2021-08-30 16:05 UTC, AntoniRomera commented
@pedrobaeza Do you think the modification I have made is correct? Instead of deleting, I have stopped the analytical lines in the test so that it does not give errors.

2021-08-31 05:45 UTC, pedrobaeza approved these changes

2021-08-31 05:45 UTC, pedrobaeza commented
/ocabot merge nobump

2021-08-31 05:55 UTC, merged