[15.0][MIG] project_parent_task_filter
OCA/project pull request #868
Opened 2021-12-14 12:47 UTC by mariadforgeflow

Migration to v15.

@ForgeFlow

2021-12-15 16:35 UTC, ChrisOForgeFlow requested changes

2021-12-15 16:35 UTC, ChrisOForgeFlow commented on project_parent_task_filter/models/project.py
> +            if vals.get("parent_id", False):
It might be a good idea to add an init hook to ensure that the historical data remains consistent.

2021-12-16 13:39 UTC, ChrisOForgeFlow approved these changes
Code Review +1

2021-12-16 14:11 UTC, tarteo approved these changes
Code LGTM, tested locally. Just one small non-blocking request

2021-12-16 14:12 UTC, tarteo commented on project_parent_task_filter/models/project.py
> +from odoo import api, models
Can you rename this file to `project_task.py`

2021-12-23 09:49 UTC, JoanMForgeFlow approved these changes
LG!

2022-01-19 13:50 UTC, emagdalenaC2i approved these changes
LGTM

2022-01-25 16:50 UTC, sbidoul commented
/ocabot migration project_parent_task_filter

2022-01-27 15:01 UTC, emagdalenaC2i commented on project_parent_task_filter/models/project_task.py
> +            "view_mode": "tree,kanban,form,calendar,pivot,graph,activity",
Could you change this? 
```suggestion
            "view_mode": "kanban,tree,form,calendar,pivot,graph,activity",
```

2022-02-02 13:33 UTC, Mantux11 approved these changes

2022-02-02 15:22 UTC, AaronHForgeFlow approved these changes
Functional review

2022-02-02 15:22 UTC, AaronHForgeFlow commented
/ocabot merge nobump

2022-02-02 15:27 UTC, merged