[14.0][IMP] project_task_pull_request: Option to show PR URI in main …
OCA/project pull request #934
Opened 2022-06-17 11:33 UTC by ilyasProgrammer

…area of task form.

2022-06-17 13:03 UTC, francesco-ooops approved these changes
Functional review ok 

This PR allows to use PR URI field without developer mode, without changing current behavior

It also clarifies in description that PR URI field is only accessible through dev mode (lost quite some time looking for it)

2022-06-17 14:29 UTC, pedrobaeza commented
Isn't better to just remove the group on existing field? FYI, we use `base_technical_features` OCA module and assign such group to everyone, as we haven't never understood the reason for hiding the fields in a "basic mode". I call it instead "limited mode".

2022-06-17 14:37 UTC, francesco-ooops commented
> Isn't better to just remove the group on existing field? FYI, we use `base_technical_features` OCA module and assign such group to everyone, as we haven't never understood the reason for hiding the fields in a "basic mode". I call it instead "limited mode".

I'll check with @ilyasProgrammer, but 
1) we didn't want to change anything from current behavior for other module users and 
2) wanted to (allow to) move the field to a more prominent position in the form, as it's easy to forget to fill a field that is in a secondary tab

(required field does not work in our case as not all tasks are development tasks)

2022-06-17 14:42 UTC, pedrobaeza commented
The module itself brings a mechanism for doing such field required when going to a certain stage. You should use such mechanism.

2022-06-17 14:51 UTC, francesco-ooops commented
> (required field does not work in our case as not all tasks are development tasks)

I find that mechanism too restrictive because it implies that all tasks must be related to a PR, while some tasks are pm related, eg: "import data" or "test with customer function x"

basically all I wanted was to have a PR field in main task form where I can quickly check if there's a PR related to the task :)

Do you think there's an easy way to achieve that?

2022-06-17 14:58 UTC, pedrobaeza commented
You select the restriction by project, so it's not restrictive at all, and you also select in which stages do you want to apply them. I have the stage "Testing" so tasks that don't require a pull request don't go through that stage.

2022-06-17 15:09 UTC, francesco-ooops commented
> You select the restriction by project, so it's not restrictive at all, and you also select in which stages do you want to apply them. I have the stage "Testing" so tasks that don't require a pull request don't go through that stage.

I understood how the module works, but it's not applicable to our flow as all projects have the same to do/processing/revision/acceptance/deploy/done stages. Some tasks have PRs from stage 1 to end, some never have them, and that's the same across projects. I appreciate the guidance anyway :)

But going back to the PR goal: all I'd like to have is a PR field in main task form where I can quickly click and move from project to github. Functionally, seemed to me this PR is a good way to proceed as it allows to maintain both current behavior and implement my request. What do you think?

2022-06-17 15:12 UTC, pedrobaeza commented
Well, it's to complicate a module and its maintenance adding parameters. If a good number of this module users want to move the field to top and to remove the technical group, you can directly propose that. I can accept such changes.

2022-06-17 15:35 UTC, francesco-ooops commented
> If a good number of this module users want to move the field to top and to remove the technical group, you can directly propose that.

I would like to do that, but it's not clear to me how such a poll should be conducted. AFAIK I don't think there's a discussion space available to OCA where I could intercept this specific module's users opinions. I could message on discord or open an issue on this repo but we know it would probably stay silent forever (understandably). So overall the solutions I see are: 

1) have a PR (this one) allowing both possibilities and get it merged. I don't think 78 lines will have much of an impact on OCA, although I understand small numbers adding up... but I don't think setting the field in a hidden tab was great design from the beginning.

2) have a PR moving the field to main form view and get it merged (those who will miss to see the PR and currently use the module and liked the field where it is... well, too bad for them)

3) keep the not-so-great design on OCA, make an internal module with the field where I want and move on :)

What would you do in my position?

2022-06-17 15:49 UTC, francesco-ooops commented
oh I forgot, would adding tests offset the maintenance technical debt? or be a good condition to take in charge mainteinance from this PR?

2022-06-17 15:52 UTC, pedrobaeza commented
I would go for 2, and those not happy can stay in a previous version of the module.

2022-06-17 15:57 UTC, francesco-ooops commented
> I would go for 2, and those not happy can stay in a previous version of the module.

alright thanks! :)

2022-06-20 06:56 UTC, pedrobaeza requested changes

2022-06-20 06:56 UTC, pedrobaeza commented on project_task_pull_request/__manifest__.py
> +        "views/project_task_pull_request_view.xml",
This shouldn't be changed.

2022-06-20 06:56 UTC, pedrobaeza commented on project_task_pull_request/readme/HISTORY.rst
> +14.0.1.0.0
Remove this

2022-06-20 06:56 UTC, pedrobaeza commented on project_task_pull_request/readme/USAGE.rst
> +#. To add a PR URI to a task, click on the task ans set it.
```suggestion
#. To add a PR URI to a task, click on the task and set it in the corresponding field in the header.
```

2022-06-20 07:08 UTC, pedrobaeza commented
The file `HISTORY.rst` is still there, although empty.

2022-06-20 07:19 UTC, pedrobaeza approved these changes

2022-06-20 07:20 UTC, pedrobaeza commented
Let's give now some time to other people to review this.

2022-06-20 08:11 UTC, francesco-ooops approved these changes
Functional review ok!

Now field is always accessible and can be selected in search bar :)

2022-06-20 08:19 UTC, pedrobaeza commented
Maybe it's good to leave the conditional visibility on the "Other information" tab

2022-06-20 08:27 UTC, francesco-ooops commented
> Maybe it's good to leave the conditional visibility on the "Other information" tab

Can you clarify how should user choose whether field should be visible or not?

2022-06-20 08:46 UTC, pedrobaeza commented
Both are shown, for old and new habits

2022-06-20 09:51 UTC, francesco-ooops commented
@pedrobaeza is it ok? currently it is displayed twice (header and extra info tab), but I'm not sure if that's the conditional visibility you were referring to

2022-06-20 09:52 UTC, pedrobaeza commented on project_task_pull_request/views/project_task_pull_request_view.xml
> -                    attrs="{'invisible':[('pr_required_states', '=', [])]}"
I mean to not touch this field and leave it as it was. Just add the other.

2022-06-20 10:04 UTC, pedrobaeza approved these changes

2022-06-20 10:29 UTC, francesco-ooops commented
@pedrobaeza good for me too! can we merge?

2022-06-20 10:35 UTC, pedrobaeza commented
No, let's wait a bit for other reviewers if they have any complain.

2022-06-22 09:25 UTC, francesco-ooops commented
tagging @OCA/project-service-maintainers to check if anyone has an opinion on this, thanks! :)

2022-06-22 14:24 UTC, leemannd approved these changes

2022-06-22 18:37 UTC, rafaelbn commented
/ocabot merge minor

2022-06-22 18:43 UTC, merged