[14.0][UPD]project_milestone: new features added
OCA/project pull request #947
Opened 2022-07-19 11:54 UTC by AshishHirapara

* New features added
    #. Subtask inherits the milestones from the parent task
    #. 'Milestone Required' field is added to project
    #. Milestone can be assigned directly from Task Kanban

2022-07-19 14:24 UTC, francesco-ooops approved these changes
Functional review ok!

2022-07-21 07:52 UTC, elvise approved these changes
LGTM!

2022-07-28 06:26 UTC, yajo requested changes
Quoting from [the docs](https://www.odoo.com/documentation/14.0/developer/howtos/rdtraining/09_compute_onchange.html):

> In many cases, both computed fields and onchanges may be used to achieve the same result. Always prefer computed fields since they are also triggered outside of the context of a form view.

Read those docs to understand the differences. I think that in this particular case, the computed writable field is a better option.

If you still prefer to keep going with onchanges, then at least attend the 2 comments below.

Thanks!

2022-07-28 06:26 UTC, yajo commented on project_milestone/models/project.py
> +    def use_milestones_onchange(self):
Onchange methods must be private, and unless there's a major reason, follow the standard of prefixing it with `_onchange_`. So it'd be something like:

```suggestion
    def _onchange_use_milestones(self):
```

2022-07-28 06:26 UTC, yajo commented on project_milestone/models/project_task.py
> +    def parent_id_milestone_onchange(self):
Just like before:

```suggestion
    def _onchange_parent_id_milestone(self):
```

2022-07-28 13:30 UTC, AshishHirapara commented on project_milestone/models/project.py
> +    def use_milestones_onchange(self):
@yajo I will go with changing the method names. Thanks for the suggestions. These are done.

2022-07-28 13:30 UTC, AshishHirapara commented on project_milestone/models/project_task.py
> +    def parent_id_milestone_onchange(self):
done

2022-07-28 13:49 UTC, francesco-ooops commented
@yajo good now?

2022-07-29 11:12 UTC, yajo approved these changes

2022-07-29 11:12 UTC, yajo commented
/ocabot merge minor

2022-07-29 11:24 UTC, merged