[13.0][IMP] project_stock: Add analytic date
OCA/project pull request #982
Opened 2022-09-15 14:09 UTC by victoralmau

The possibility of set a specific date in project or task has been added so that if it is set it will be used in analytic items linked to materials.

Please @pedrobaeza and @chienandalu can you review it?

@Tecnativa TT38988

2022-09-15 15:00 UTC, chienandalu approved these changes
LGTM :+1:

2022-09-15 17:39 UTC, pedrobaeza requested changes

2022-09-15 17:39 UTC, pedrobaeza commented on project_stock/i18n/es.po
> +msgstr "Fecha de contabilidad analítica"
```suggestion
msgstr "Fecha para analítica"
```

2022-09-15 17:39 UTC, pedrobaeza commented on project_stock/tests/test_project_stock.py
> +            self.task.project_id.stock_analytic_date,
Fixed values, please

2022-09-16 06:20 UTC, victoralmau commented
Changes done.

2022-09-16 07:10 UTC, pedrobaeza approved these changes

2022-09-16 07:10 UTC, pedrobaeza commented
/ocabot merge minor

2022-09-16 07:53 UTC, merged